# Pandas

A biblioteca Pandas é uma das mais populares e poderosas ferramentas para manipulação e análise de dados em Python. Ela oferece estruturas de dados flexíveis, como DataFrames, que permitem organizar, limpar, transformar e explorar grandes volumes de dados de forma intuitiva. Com Pandas, é possível realizar operações como filtragem, agregação e fusão de dados com facilidade, sendo indispensável em qualquer fluxo de trabalho analítico.

## Introdução à Biblioteca Pandas

Documentação oficial: [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.html)

### Tipos de Dados que o Pandas Suporta

O Pandas é adequado para muitos formatos e tipos de dados, incluindo:

- Dados tabulares com colunas de tipos heterogêneos (como planilhas Excel ou tabelas SQL)

- Dados de séries temporais (ordenadas ou não, com ou sem frequência fixa)

- Matrizes com rótulos de linha e coluna, homogêneas ou heterogêneas

- Conjuntos de dados estatísticos ou observacionais (mesmo sem rótulos explícitos)

### Principais Funcionalidades do Pandas

- Manipulação fácil de dados ausentes, tanto para valores float quanto de outros tipos

- Mutabilidade de tamanho: é possível inserir ou remover colunas de um DataFrame ou objetos de dimensão superior com facilidade

- Agrupamento poderoso de dados, permitindo operações do tipo:

    - Divisão-aplicação-combinação

    - Agregações

    - Transformações

- Conversão facilitada de dados irregulares ou com indexações diferentes (de estruturas como listas, dicionários ou arrays NumPy) para objetos DataFrame

- Junção intuitiva de conjuntos de dados, útil para mesclar ou combinar informações de fontes distintas

- Remodelagem e criação de pivôs de dados de forma flexível, possibilitando reorganizar a estrutura de tabelas

- Rotulagem hierárquica de eixos, permitindo múltiplos níveis de índices (MultiIndex) nas linhas ou colunas

- Ferramentas robustas de leitura e escrita de arquivos, suportando diversos formatos como:

    - Arquivos de texto (CSV e delimitados)

    - Arquivos do Excel

    - Bancos de dados

    - Outros formatos estruturados

- Funcionalidades específicas para séries temporais, incluindo:

    - Geração de intervalos de datas

    - Conversão de frequência de dados

    - Estatísticas de janelas móveis

    - Deslocamento e atraso de datas

## DataFrame

Um DataFrame transforma dados brutos do Python, como dicionários, em uma estrutura tabular organizada (linhas e colunas), podendo também representar arquivos de tabela, como CSV ou Excel.

- É uma estrutura bidimensional: possui linhas e colunas.

- As colunas podem conter tipos de dados diferentes (como strings, inteiros, etc.).

- As colunas do DataFrame são do tipo Série, onde cada coluna é uma Série, e o conjunto de Séries forma o DataFrame.

- Pode ser manipulado como um array (pelos índices) ou como um dicionário (pelos nomes das colunas).

In [25]:
import pandas as pd

# Exemplo 1: Transformando um dicionário em DataFrame

informacoes = { # dicionário
    "Nome": [
        "Felipe Orlando",
        "Lucas Kataque",
        "Pedro Juliane",
        "Rafael Monteiro"
    ],
    "Salario": [2600, 4300, 5400, 3100],
    "Profissao": ["Mecânico", "Engenheiro", "Médico", "Químico"]
}

df = pd.DataFrame(informacoes) # criar o nosso DataFrame
df # mostrar o DataFrame

              Nome  Salario   Profissao
0   Felipe Orlando     2600    Mecânico
1    Lucas Kataque     4300  Engenheiro
2    Pedro Juliane     5400      Médico
3  Rafael Monteiro     3100     Químico

#### Detalhes sobre a Base de Dados que será abordada daqui para frente:

Esta base de dados contém informações coletadas de uma plataforma de pedidos de comida online ao longo de um período de tempo. Ele abrange vários atributos relacionados à Ocupação, Tamanho da Família, Feedback, entre outros.

-**Idade:** Idade do cliente.

-**Gênero:** Gênero do cliente.

-**Estado Civil:** Estado civil do cliente.

-**Ocupação:** Ocupação do cliente.

-**Renda Mensal:** Renda mensal do cliente.

-**Escolaridade:** Qualificações educacionais do cliente.

-**Tamanho da Família:** Número de pessoas na família do cliente.

-**Latitude:** Latitude da localização do cliente.

-**Longitude:** Longitude da localização do cliente
.
-**Código Postal:** Código postal da localização do cliente.

-**Status do Pedido:** Situação atual do pedido (ex.: pendente, confirmado, entregue).

-**Feedback:** Feedback fornecido pelo cliente após receber o pedido.

-**Unnamed: 12:**: Não se sabe o que é, deve ter sido algum erro, então removeremos essa coluna posteriormente.

In [26]:
import pandas as pd
# Exemplo 2: Transformando um arquivo em DataFrame

BASE = "dados/onlinefoods.csv" # variavel para a nossa base de dados
df = pd.read_csv(BASE) # para ler aquivo csv
df # mostrar o DataFrame

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

## Funções de Checagem de Dados

Antes de realizar análises mais profundas, é importante garantir que os dados da base estejam coerentes, completos e bem estruturados. Essas checagens ajudam a validar se os dados foram importados corretamente e servem como base para levantamentos e questionamentos futuros.

- **Exibição do DataFrame:**

    - `df.head()` → Exibe as 5 primeiras linhas da base de dados (pode receber um número como argumento para exibir mais ou menos linhas).

    - `df.tail()` → Exibe as 5 últimas linhas da base (também aceita um número como argumento).

- **Checagens Essenciais:**

    As primeiras checagens que devem ser feitas ao abrir um DataFrame. Servem para confirmar se o formato da base está correto, se todas as colunas foram carregadas corretamente e se há dados ausentes.

    - `df.shape` → Verifica o tamanho da base (linhas e colunas), para confirmar se corresponde ao esperado.

    - `df.columns` → Exibe o nome de todas as colunas da base.

    - `df.info()` → Mostra o tipo de dado de cada coluna, útil para identificar inconsistências (como colunas numéricas contendo texto, por exemplo).

    - `df.isnull().sum()` → Mostra quantos valores nulos existem em cada coluna.

    Verificar valores muito altos, muito baixos ou fora do esperado é fundamental para identificar erros ou anomalias nos dados.

    - `df.describe()` → Exibe estatísticas descritivas das colunas numéricas do DataFrame, como contagem (`count`), média (`mean`), desvio padrão (`std`), valor mínimo (min), percentis (`25%`, `50%`, `75%`) e valor máximo (`max`). É útil para identificar possíveis valores extremos, incoerentes ou fora do esperado nas variáveis numéricas.

    - `df.describe(exclude="number")` → Exibe estatísticas descritivas apenas das colunas não numéricas, como variáveis do tipo string (objetos). Mostra, por exemplo, a contagem de valores (`count`), número de valores únicos (`unique`), valor mais frequente (`top`) e a frequência desse valor (`freq`). Serve para entender melhor o comportamento e a distribuição de dados categóricos ou textuais.

    Uma maneira de detectar rapidamente codificações específicas de dados ausentes ou valores inválidos.

    - `(df.select_dtypes("number") == valor).sum()` → Conta quantas vezes o valor `valor` aparece nas colunas numéricas.

- **Checagem de Valores Únicos e Categorias:**

    Entender a quantidade e variedade de valores em cada coluna é importante para analisar a qualidade dos dados categóricos.

    - `df.nunique()` → Conta quantos valores únicos existem em cada coluna.

    - `df["nome_coluna"].unique()` → Mostra todas as categorias distintas da coluna 'nome_coluna' (sem repetição).

    - `df["nome_coluna"].nunique()` → Mostra quantas categorias diferentes existem na coluna 'nome_coluna'.

- **Duplicações:**

    Linhas duplicadas indicam dados redundantes e podem distorcer as análises.

    - `df.duplicated().sum()` → Conta quantas linhas da base estão totalmente duplicadas (registro completo repetido).

- **Frequência de Valores:**

    Saber quantas vezes cada valor aparece em uma coluna ajuda a entender a distribuição dos dados categóricos.

    - `df["nome_coluna"].value_counts()` → Conta quantas vezes cada valor da coluna 'nome_coluna' aparece na base.


Agora, vamos abordar cada um dos exemplos para entender melhor como essas funções funcionam na prática.

In [27]:
import pandas as pd

# Primeiro passo é importar nossa base de dados

BASE = "dados/onlinefoods.csv"
df = pd.read_csv(BASE)

In [28]:
df.head() # imprime as 5 primeiras linhas

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes

In [36]:
df.tail(10) # imprime as 10 últimas linhas

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
378,23,Female,Single,Employee,25001 to 50000,Post Graduate,2,12.9847,77.5491,560100,Yes,Positive,Yes
379,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
380,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes
381,22,Male,Single,Student,No Income,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
382,24,Female,Single,Student,No Income,Post Graduate,3,12.9828,77.6131,560042,Yes,Positive,Yes
383,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

In [30]:
df.shape # quantidade de linhas e colunas

(388, 13)

In [31]:
df.columns # nome de todas as colunas

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', 'Unnamed: 12'],
      dtype='object')

In [37]:
df.info() # tipo de cada coluna e quantidade de valores não nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    object
 2   Marital Status              388 non-null    object
 3   Occupation                  388 non-null    object
 4   Monthly Income              388 non-null    object
 5   Educational Qualifications  388 non-null    object
 6   Family size                 388 non-null    int64
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64
 10  Output                      388 non-null    object
 11  Feedback                    388 non-null    object
 12  Unnamed: 12                 388 non-null    object
dtypes: float64(2), int64(3), object(8)
memory usage: 39.5+ KB

In [38]:
df.isnull().sum() # quantidade de valores nulos por coluna

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
Unnamed: 12                   0
dtype: int64

In [ ]:
df.describe() # descrição das colunas numéricas

              Age  Family size    latitude   longitude       Pin code
count  388.000000   388.000000  388.000000  388.000000     388.000000
mean    24.628866     3.280928   12.972058   77.600160  560040.113402
std      2.975593     1.351025    0.044489    0.051354      31.399609
min     18.000000     1.000000   12.865200   77.484200  560001.000000
25%     23.000000     2.000000   12.936900   77.565275  560010.750000
50%     24.000000     3.000000   12.977000   77.592100  560033.500000
75%     26.000000     4.000000   12.997025   77.630900  560068.000000
max     33.000000     6.000000   13.102000   77.758200  560109.000000

In [ ]:
df.describe(exclude="number") # descrição das colunas não numéricas

,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Output,Feedback,Unnamed: 12
count,388,388,388,388,388,388,388,388
unique,2,3,4,5,5,2,2,2
top,Male,Single,Student,No Income,Graduate,Yes,Positive,Yes
freq,222,268,207,187,177,301,317,301

In [ ]:
(df.select_dtypes("number") == 4).sum() # saber quantas vezes o número 4 aparece nas colunas numéricas

Age             0
Family size    63
latitude        0
longitude       0
Pin code        0
dtype: int64

In [46]:
df.nunique() # quantidade de valores diferentes em cada coluna

Age                           16
Gender                         2
Marital Status                 3
Occupation                     4
Monthly Income                 5
Educational Qualifications     5
Family size                    6
latitude                      77
longitude                     76
Pin code                      77
Output                         2
Feedback                       2
Unnamed: 12                    2
dtype: int64

In [48]:
df['Monthly Income'].unique() # mostra quais são os valores diferentes da coluna 'Monthly Income'

array(['No Income', 'Below Rs.10000', 'More than 50000', '10001 to 25000',
       '25001 to 50000'], dtype=object)

In [50]:
df['Monthly Income'].nunique() # mostra a quantidade de valores diferentes da coluna 'Monthly Income'

5

In [ ]:
df.duplicated() # quantidade de linhas duplicadas existentes no DataFrame

0      False
1      False
2      False
3      False
4      False
       ...
383     True
384     True
385     True
386    False
387     True
Length: 388, dtype: bool

In [ ]:
df['Monthly Income'].value_counts() # conta quantas vezes cada valor aparece

Monthly Income
No Income          187
25001 to 50000      69
More than 50000     62
10001 to 25000      45
Below Rs.10000      25
Name: count, dtype: int64

#### Conclusões nas Primeiras Análises

O uso do `df.shape` e do `df.columns` revelou que há uma coluna a mais do que o esperado na base de dados: a coluna 'Unnamed: 12'. Essa coluna deverá ser removida posteriormente para evitar que interfira na análise dos dados.

As funções `df.info()` e `df.isnull().sum()` mostraram que os tipos de dados de cada coluna estão corretos e que não existem valores nulos, indicando que não será necessário aplicar tratamentos adicionais neste momento.

As funções `df.describe()` e `df.describe(exclude="number")` foram utilizadas para obter uma visão geral dos dados numéricos e não numéricos. A análise inicial não apontou a presença de outliers e permitiu compreender melhor a distribuição das categorias.

A função `df.nunique()` auxiliou na verificação da quantidade de valores únicos em cada coluna. Em casos de colunas que deveriam conter apenas valores únicos, como IDs, essa função seria essencial para identificar possíveis erros. No entanto, nesse DataFrame, os dados parecem estar consistentes.

A função `df.duplicated()` indicou a existência de diversas linhas duplicadas, o que pode demonstrar a existência de padrões de comportamento entre os clientes analisados.