# Pandas

A biblioteca Pandas é uma das mais populares e poderosas ferramentas para manipulação e análise de dados em Python. Ela oferece estruturas de dados flexíveis, como DataFrames, que permitem organizar, limpar, transformar e explorar grandes volumes de dados de forma intuitiva. Com Pandas, é possível realizar operações como filtragem, agregação e fusão de dados com facilidade, sendo indispensável em qualquer fluxo de trabalho analítico.

## Introdução à Biblioteca Pandas

Documentação oficial: [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.html)

### Tipos de Dados que o Pandas Suporta

O Pandas é adequado para muitos formatos e tipos de dados, incluindo:

- Dados tabulares com colunas de tipos heterogêneos (como planilhas Excel ou tabelas SQL)

- Dados de séries temporais (ordenadas ou não, com ou sem frequência fixa)

- Matrizes com rótulos de linha e coluna, homogêneas ou heterogêneas

- Conjuntos de dados estatísticos ou observacionais (mesmo sem rótulos explícitos)

### Principais Funcionalidades do Pandas

- Manipulação fácil de dados ausentes, tanto para valores float quanto de outros tipos

- Mutabilidade de tamanho: é possível inserir ou remover colunas de um DataFrame ou objetos de dimensão superior com facilidade

- Agrupamento poderoso de dados, permitindo operações do tipo:

    - Divisão-aplicação-combinação

    - Agregações

    - Transformações

- Conversão facilitada de dados irregulares ou com indexações diferentes (de estruturas como listas, dicionários ou arrays NumPy) para objetos DataFrame

- Junção intuitiva de conjuntos de dados, útil para mesclar ou combinar informações de fontes distintas

- Remodelagem e criação de pivôs de dados de forma flexível, possibilitando reorganizar a estrutura de tabelas

- Rotulagem hierárquica de eixos, permitindo múltiplos níveis de índices (MultiIndex) nas linhas ou colunas

- Ferramentas robustas de leitura e escrita de arquivos, suportando diversos formatos como:

    - Arquivos de texto (CSV e delimitados)

    - Arquivos do Excel

    - Bancos de dados

    - Outros formatos estruturados

- Funcionalidades específicas para séries temporais, incluindo:

    - Geração de intervalos de datas

    - Conversão de frequência de dados

    - Estatísticas de janelas móveis

    - Deslocamento e atraso de datas

## DataFrame

Um DataFrame transforma dados brutos do Python, como dicionários, em uma estrutura tabular organizada (linhas e colunas), podendo também representar arquivos de tabela, como CSV ou Excel.

- É uma estrutura bidimensional: possui linhas e colunas.

- As colunas podem conter tipos de dados diferentes (como strings, inteiros, etc.).

- As colunas do DataFrame são do tipo Série, onde cada coluna é uma Série, e o conjunto de Séries forma o DataFrame.

- Pode ser manipulado como um array (pelos índices) ou como um dicionário (pelos nomes das colunas).

In [25]:
import pandas as pd

# Exemplo 1: Transformando um dicionário em DataFrame

informacoes = { # dicionário
    "Nome": [
        "Felipe Orlando",
        "Lucas Kataque",
        "Pedro Juliane",
        "Rafael Monteiro"
    ],
    "Salario": [2600, 4300, 5400, 3100],
    "Profissao": ["Mecânico", "Engenheiro", "Médico", "Químico"]
}

df = pd.DataFrame(informacoes) # criar o nosso DataFrame
df # mostrar o DataFrame

              Nome  Salario   Profissao
0   Felipe Orlando     2600    Mecânico
1    Lucas Kataque     4300  Engenheiro
2    Pedro Juliane     5400      Médico
3  Rafael Monteiro     3100     Químico

#### Detalhes sobre a Base de Dados que será abordada daqui para frente:

Esta base de dados contém informações coletadas de uma plataforma de pedidos de comida online ao longo de um período de tempo. Ele abrange vários atributos relacionados à Ocupação, Tamanho da Família, Feedback, entre outros.

-**Idade:** Idade do cliente.

-**Gênero:** Gênero do cliente.

-**Estado Civil:** Estado civil do cliente.

-**Ocupação:** Ocupação do cliente.

-**Renda Mensal:** Renda mensal do cliente.

-**Escolaridade:** Qualificações educacionais do cliente.

-**Tamanho da Família:** Número de pessoas na família do cliente.

-**Latitude:** Latitude da localização do cliente.

-**Longitude:** Longitude da localização do cliente
.
-**Código Postal:** Código postal da localização do cliente.

-**Status do Pedido:** Situação atual do pedido (ex.: pendente, confirmado, entregue).

-**Feedback:** Feedback fornecido pelo cliente após receber o pedido.

-**Unnamed: 12:**: Não se sabe o que é, deve ter sido algum erro, então removeremos essa coluna posteriormente.

In [26]:
import pandas as pd
# Exemplo 2: Transformando um arquivo em DataFrame

BASE = "dados/onlinefoods.csv" # variavel para a nossa base de dados
df = pd.read_csv(BASE) # para ler aquivo csv
df # mostrar o DataFrame

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

## Funções de Checagem de Dados

Antes de realizar análises mais profundas, é importante garantir que os dados da base estejam coerentes, completos e bem estruturados. Essas checagens ajudam a validar se os dados foram importados corretamente e servem como base para levantamentos e questionamentos futuros.

- **Exibição do DataFrame:**

    - `df.head()` → Exibe as 5 primeiras linhas da base de dados (pode receber um número como argumento para exibir mais ou menos linhas).

    - `df.tail()` → Exibe as 5 últimas linhas da base (também aceita um número como argumento).

- **Checagens Essenciais:**

    As primeiras checagens que devem ser feitas ao abrir um DataFrame. Servem para confirmar se o formato da base está correto, se todas as colunas foram carregadas corretamente e se há dados ausentes.

    - `df.shape` → Verifica o tamanho da base (linhas e colunas), para confirmar se corresponde ao esperado.

    - `df.columns` → Exibe o nome de todas as colunas da base.

    - `df.info()` → Mostra o tipo de dado de cada coluna, útil para identificar inconsistências (como colunas numéricas contendo texto, por exemplo).

    - `df.isnull().sum()` → Mostra quantos valores nulos existem em cada coluna.

    Verificar valores muito altos, muito baixos ou fora do esperado é fundamental para identificar erros ou anomalias nos dados.

    - `df.describe()` → Exibe estatísticas descritivas das colunas numéricas do DataFrame, como contagem (`count`), média (`mean`), desvio padrão (`std`), valor mínimo (min), percentis (`25%`, `50%`, `75%`) e valor máximo (`max`). É útil para identificar possíveis valores extremos, incoerentes ou fora do esperado nas variáveis numéricas.

    - `df.describe(exclude="number")` → Exibe estatísticas descritivas apenas das colunas não numéricas, como variáveis do tipo string (objetos). Mostra, por exemplo, a contagem de valores (`count`), número de valores únicos (`unique`), valor mais frequente (`top`) e a frequência desse valor (`freq`). Serve para entender melhor o comportamento e a distribuição de dados categóricos ou textuais.

    Uma maneira de detectar rapidamente codificações específicas de dados ausentes ou valores inválidos.

    - `(df.select_dtypes("number") == valor).sum()` → Conta quantas vezes o valor `valor` aparece nas colunas numéricas.

- **Checagem de Valores Únicos e Categorias:**

    Entender a quantidade e variedade de valores em cada coluna é importante para analisar a qualidade dos dados categóricos.

    - `df.nunique()` → Conta quantos valores únicos existem em cada coluna.

    - `df["nome_coluna"].unique()` → Mostra todas as categorias distintas da coluna 'nome_coluna' (sem repetição).

    - `df["nome_coluna"].nunique()` → Mostra quantas categorias diferentes existem na coluna 'nome_coluna'.

- **Duplicações:**

    Linhas duplicadas indicam dados redundantes e podem distorcer as análises.

    - `df.duplicated().sum()` → Conta quantas linhas da base estão totalmente duplicadas (registro completo repetido).

- **Frequência de Valores:**

    Saber quantas vezes cada valor aparece em uma coluna ajuda a entender a distribuição dos dados categóricos.

    - `df["nome_coluna"].value_counts()` → Conta quantas vezes cada valor da coluna 'nome_coluna' aparece na base.


Agora, vamos abordar cada um dos exemplos para entender melhor como essas funções funcionam na prática.

In [27]:
import pandas as pd

# Primeiro passo é importar nossa base de dados

BASE = "dados/onlinefoods.csv"
df = pd.read_csv(BASE)

In [28]:
df.head() # imprime as 5 primeiras linhas

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes

In [36]:
df.tail(10) # imprime as 10 últimas linhas

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
378,23,Female,Single,Employee,25001 to 50000,Post Graduate,2,12.9847,77.5491,560100,Yes,Positive,Yes
379,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
380,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes
381,22,Male,Single,Student,No Income,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
382,24,Female,Single,Student,No Income,Post Graduate,3,12.9828,77.6131,560042,Yes,Positive,Yes
383,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

In [30]:
df.shape # quantidade de linhas e colunas

(388, 13)

In [31]:
df.columns # nome de todas as colunas

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', 'Unnamed: 12'],
      dtype='object')

In [37]:
df.info() # tipo de cada coluna e quantidade de valores não nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    object
 2   Marital Status              388 non-null    object
 3   Occupation                  388 non-null    object
 4   Monthly Income              388 non-null    object
 5   Educational Qualifications  388 non-null    object
 6   Family size                 388 non-null    int64
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64
 10  Output                      388 non-null    object
 11  Feedback                    388 non-null    object
 12  Unnamed: 12                 388 non-null    object
dtypes: float64(2), int64(3), object(8)
memory usage: 39.5+ KB

In [38]:
df.isnull().sum() # quantidade de valores nulos por coluna

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
Unnamed: 12                   0
dtype: int64

In [ ]:
df.describe() # descrição das colunas numéricas

              Age  Family size    latitude   longitude       Pin code
count  388.000000   388.000000  388.000000  388.000000     388.000000
mean    24.628866     3.280928   12.972058   77.600160  560040.113402
std      2.975593     1.351025    0.044489    0.051354      31.399609
min     18.000000     1.000000   12.865200   77.484200  560001.000000
25%     23.000000     2.000000   12.936900   77.565275  560010.750000
50%     24.000000     3.000000   12.977000   77.592100  560033.500000
75%     26.000000     4.000000   12.997025   77.630900  560068.000000
max     33.000000     6.000000   13.102000   77.758200  560109.000000

In [ ]:
df.describe(exclude="number") # descrição das colunas não numéricas

,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Output,Feedback,Unnamed: 12
count,388,388,388,388,388,388,388,388
unique,2,3,4,5,5,2,2,2
top,Male,Single,Student,No Income,Graduate,Yes,Positive,Yes
freq,222,268,207,187,177,301,317,301

In [ ]:
(df.select_dtypes("number") == 4).sum() # saber quantas vezes o número 4 aparece nas colunas numéricas

Age             0
Family size    63
latitude        0
longitude       0
Pin code        0
dtype: int64

In [46]:
df.nunique() # quantidade de valores diferentes em cada coluna

Age                           16
Gender                         2
Marital Status                 3
Occupation                     4
Monthly Income                 5
Educational Qualifications     5
Family size                    6
latitude                      77
longitude                     76
Pin code                      77
Output                         2
Feedback                       2
Unnamed: 12                    2
dtype: int64

In [48]:
df['Monthly Income'].unique() # mostra quais são os valores diferentes da coluna 'Monthly Income'

array(['No Income', 'Below Rs.10000', 'More than 50000', '10001 to 25000',
       '25001 to 50000'], dtype=object)

In [50]:
df['Monthly Income'].nunique() # mostra a quantidade de valores diferentes da coluna 'Monthly Income'

5

In [ ]:
df.duplicated() # quantidade de linhas duplicadas existentes no DataFrame

0      False
1      False
2      False
3      False
4      False
       ...
383     True
384     True
385     True
386    False
387     True
Length: 388, dtype: bool

In [ ]:
df['Monthly Income'].value_counts() # conta quantas vezes cada valor aparece

Monthly Income
No Income          187
25001 to 50000      69
More than 50000     62
10001 to 25000      45
Below Rs.10000      25
Name: count, dtype: int64

#### Conclusões nas Primeiras Análises

O uso do `df.shape` e do `df.columns` revelou que há uma coluna a mais do que o esperado na base de dados: a coluna 'Unnamed: 12'. Essa coluna deverá ser removida posteriormente para evitar que interfira na análise dos dados.

As funções `df.info()` e `df.isnull().sum()` mostraram que os tipos de dados de cada coluna estão corretos e que não existem valores nulos, indicando que não será necessário aplicar tratamentos adicionais neste momento.

As funções `df.describe()` e `df.describe(exclude="number")` foram utilizadas para obter uma visão geral dos dados numéricos e não numéricos. A análise inicial não apontou a presença de outliers e permitiu compreender melhor a distribuição das categorias.

A função `df.nunique()` auxiliou na verificação da quantidade de valores únicos em cada coluna. Em casos de colunas que deveriam conter apenas valores únicos, como IDs, essa função seria essencial para identificar possíveis erros. No entanto, nesse DataFrame, os dados parecem estar consistentes.

A função `df.duplicated()` indicou a existência de diversas linhas duplicadas, o que pode demonstrar a existência de padrões de comportamento entre os clientes analisados.

## Selecionando Partes específicas do DataFrame

- Ao trabalhar com conjuntos de dados no Pandas, é comum que apenas uma parte das informações seja relevante para uma determinada análise. Seja para investigar registros específicos, aplicar filtros com base em condições ou manipular subconjuntos de colunas, a capacidade de selecionar partes de um DataFrame é essencial. Essa prática permite reduzir a complexidade dos dados, destacar padrões e encontrar relações que passariam despercebidas em uma análise mais superficial.

- Dominar as diferentes formas de seleção, seja por índice, nome ou condição lógica, proporciona mais controle sobre o processo analítico. Com isso, é possível aplicar filtros personalizados, comparar grupos, localizar valores extremos e preparar os dados para etapas posteriores, como visualização ou modelagem. Esse tipo de operação é a base de qualquer exploração eficiente de dados e contribui significativamente para a clareza e objetividade das análises realizadas.

In [3]:
import pandas as pd

# Primeiro passo é importar nossa base de dados

BASE = "dados/onlinefoods.csv"
df = pd.read_csv(BASE)

- **Selecionar por maior ou menor valor ou index**

    - `.max()` → Pega o maior valor de uma determinada coluna

    - `.min()` → Pega o menor valor de uma determinada coluna

    - `.idxmax()` → Pega o índice do maior valor de uma determinada coluna

    - `.idxmin()` → Pega o índice do menor valor de uma determinada coluna

No exemplo abaixo, iremos selecionar os valores e index da coluna **Family size**

In [ ]:
# Criação das variáveis 
maior_valor = df['Family size'].max() # maior valor
menor_valor = df['Family size'].min() # menor valor
maior_index = df['Family size'].idxmax() # maior index
menor_index = df['Family size'].idxmin() # menor index

# Print no terminal
print(f'Maior valor: {maior_valor}')
print(f'Menor valor: {menor_valor}')
print(f'Maior index: {maior_index}')
print(f'Menor index: {menor_index}')

Maior valor: 6
Menor valor: 1
Maior index: 3
Menor index: 19

- **Selecionar linhas e colunas por `iloc` e `loc`**

    - **`.loc`** → Seleciona linhas e colunas por nome   

    - **`.iloc`** → Seleciona linhas e colunas por índice

Abaixo serão mostrados 3 exemplos para o uso do `loc` e outros 3 para `iloc`

In [20]:
# Exemplo 1 de loc:

df.loc[0:3] # Pega da linha 0 até a linha 3 e todas as colunas -> nesse caso, como o loc pega por nome ele acaba pegando a linha 3 também

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes

In [ ]:
# Exemplo 2 de loc:

df.loc[0:5, ['Age', 'Family size']] # Pega da linha 0 até a 5 e apenas as colunas 'Age' e 'Family size'

   Age  Family size
0   20            4
1   24            3
2   22            3
3   22            6
4   22            4
5   27            2

In [ ]:
# Exemplo 3 de loc:

df.loc[df['Age'].idxmax()] # Pega o índice da fileira que possui o maior valor de idade ('Age') e printa a fileira inteira

Age                                        33
Gender                                   Male
Marital Status                        Married
Occupation                           Employee
Monthly Income                More than 50000
Educational Qualifications               Ph.D
Family size                                 5
latitude                               12.998
longitude                             77.6227
Pin code                               560005
Output                                     No
Feedback                            Negative
Unnamed: 12                                No
Name: 137, dtype: object

In [ ]:
# Exemplo 1 de iloc:

df.iloc[0:3] # Pega da linha 0 até a 2 com todas as colunas -> Como iloc pega por índice, ele acaba pegando sempre uma a menos

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes

In [ ]:
# Exeemplo 2 de iloc:

df.iloc[10:15, 0:3] # Pega da linha 10 até a 15 e as colunas 0 (Age), 1 (Gender) e 2 (Marital Status)

    Age  Gender Marital Status
10   22  Female         Single
11   23    Male         Single
12   23    Male         Single
13   21    Male         Single
14   23  Female         Single

In [ ]:
# Exemplo 3 de iloc:

df.iloc[0:5, [0, 2]] # Pega da linha 0 até a 4 e as colunas 0 (Age) e 2 (Marital Status)

   Age Marital Status
0   20         Single
1   24         Single
2   22         Single
3   22         Single
4   22         Single

- **Selecionar por condições (parecido com `if`)**

    - A ideia é mostrar como fazer filtros em DataFrames usando condições, como por exemplo `>`, `==`, ou até combinações com `and`, `or` e `not`. Isso permite selecionar só as linhas que atendem a certos critérios. 

        - Vale lembrar que, nesse caso, usamos `&` no lugar de `and`, `|` no lugar de `or` e `~` no lugar de `not`, sempre com os parênteses envolvendo cada condição. 
    
    - Também é possível usar o `.isin()` para checar se um valor está dentro de uma lista.

In [ ]:
# Exemeplo 1: Utilizando condições

df[df['Age'] > 31][['Age', 'Monthly Income', 'Educational Qualifications']] # Apenas as informações das colunas 'Age', 'Monthly Income' e 'Educational Qualifications' quando a idade for maior que 31

     Age   Monthly Income Educational Qualifications
37    32        No Income                   Graduate
99    32        No Income                 Uneducated
118   32   25001 to 50000                   Graduate
123   32  More than 50000                       Ph.D
131   32  More than 50000                   Graduate
137   33  More than 50000                       Ph.D
148   32   10001 to 25000                   Graduate
157   32        No Income                   Graduate
184   32        No Income                     School
215   32   10001 to 25000                     School
223   32  More than 50000                   Graduate
229   32   25001 to 50000                   Graduate
240   32  More than 50000              Post Graduate
310   32  More than 50000                   Graduate
316   32   25001 to 50000                   Graduate
327   32  More than 50000              Post Graduate
358   32   25001 to 50000                   Graduate

In [ ]:
# Exemeplo 2: Utilizando condições com operador or

df[(df['Family size'] == 6) | (df['Monthly Income'] == 'More than 50000')] # Apenas se o tamanho da família seja igual a 6 ou tenha um ganho mensal maior que 50000

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
5,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes
15,24,Female,Single,Student,No Income,Post Graduate,6,12.8893,77.6399,560068,Yes,Positive,Yes
32,25,Male,Married,Employee,More than 50000,Ph.D,4,12.9261,77.6221,560034,Yes,Positive,Yes
40,30,Male,Married,Self Employeed,More than 50000,Uneducated,4,12.9662,77.6068,560025,Yes,Negative,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,12.9369,77.6407,560095,Yes,Positive,Yes
373,30,Male,Married,Self Employeed,More than 50000,Graduate,1,13.0809,77.5565,560097,No,Negative,No
375,26,Female,Married,Employee,Below Rs.10000,Graduate,6,12.9859,77.6713,560093,No,Negative,No
376,25,Male,Single,Self Employeed,More than 50000,School,3,12.9859,77.6713,560093,Yes,Positive,Yes
380,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes

In [ ]:
# Exemeplo 3: Utilizando condições com operador and e not

df[(df['Age'] == 19) & ~(df['Gender'] == 'Female')] # Caso idade seja igual a 19 e não seja mulher

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
133,19,Male,Single,Student,No Income,Graduate,2,13.0019,77.5713,560003,No,Negative,No
196,19,Male,Single,Student,No Income,Graduate,6,12.9442,77.6076,560030,Yes,Positive,Yes
280,19,Male,Single,Student,No Income,Graduate,6,12.9048,77.6821,560036,Yes,Positive,Yes

In [ ]:
# Exemeplo 4: Utilizando método isin

df[df['Occupation'].isin(['Self Employeed', 'House wife'])] # Mostra todas as fileiras que possuirem 'Self Employeed' e 'House wife' na coluna 'Occupation'

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
14,23,Female,Single,Self Employeed,10001 to 25000,Post Graduate,5,12.9438,77.5738,560004,Yes,Positive,Yes
37,32,Female,Prefer not to say,House wife,No Income,Graduate,5,12.9820,77.6256,560008,Yes,Negative,Yes
40,30,Male,Married,Self Employeed,More than 50000,Uneducated,4,12.9662,77.6068,560025,Yes,Negative,Yes
45,27,Female,Married,Self Employeed,10001 to 25000,Post Graduate,2,12.9261,77.6221,560034,Yes,Positive,Yes
89,28,Male,Married,Self Employeed,10001 to 25000,Graduate,2,13.0289,77.5400,560022,No,Negative,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,29,Male,Single,Self Employeed,More than 50000,Graduate,6,12.8845,77.6036,560076,Yes,Positive,Yes
361,24,Female,Single,Self Employeed,25001 to 50000,Post Graduate,3,13.0103,77.5796,560080,No,Negative,No
362,26,Male,Prefer not to say,Self Employeed,More than 50000,Post Graduate,2,13.0103,77.5796,560080,Yes,Positive,Yes
373,30,Male,Married,Self Employeed,More than 50000,Graduate,1,13.0809,77.5565,560097,No,Negative,No
376,25,Male,Single,Self Employeed,More than 50000,School,3,12.9859,77.6713,560093,Yes,Positive,Yes

## Selecionando Partes específicas do DataFrame com Query

- O método `query()` do Pandas permite filtrar linhas de um DataFrame com base em condições, de forma muito parecida com o que já foi feito usando colchetes e operadores lógicos. A principal vantagem do `query()` é deixar o código mais limpo e legível, especialmente quando estamos trabalhando com várias condições ao mesmo tempo.

- Tudo o que foi apresentado na parte de seleção com condições pode ser reescrito usando `query()`, com o benefício de uma sintaxe mais próxima da linguagem natural. No fim das contas, usar `query()` ou a notação tradicional com colchetes é uma escolha do programador, o importante é optar pela forma que torne o código mais claro para quem vai ler e manter depois.

Abaixo serão mostrados os mesmos exemplos, porém agora utilizando o método `query()`.

In [ ]:
# Exemeplo 1: Utilizando condições

# Antes:
df[df['Age'] > 31][['Age', 'Monthly Income', 'Educational Qualifications']] # Apenas as informações das colunas 'Age', 'Monthly Income' e 'Educational Qualifications' quando a idade for maior que 31

# Depois:
df.query("Age > 31")[['Age', 'Monthly Income', 'Educational Qualifications']]

     Age   Monthly Income Educational Qualifications
37    32        No Income                   Graduate
99    32        No Income                 Uneducated
118   32   25001 to 50000                   Graduate
123   32  More than 50000                       Ph.D
131   32  More than 50000                   Graduate
137   33  More than 50000                       Ph.D
148   32   10001 to 25000                   Graduate
157   32        No Income                   Graduate
184   32        No Income                     School
215   32   10001 to 25000                     School
223   32  More than 50000                   Graduate
229   32   25001 to 50000                   Graduate
240   32  More than 50000              Post Graduate
310   32  More than 50000                   Graduate
316   32   25001 to 50000                   Graduate
327   32  More than 50000              Post Graduate
358   32   25001 to 50000                   Graduate

In [70]:
# Exemeplo 2: Utilizando condições com operador or

# Antes:
df[(df['Family size'] == 6) | (df['Monthly Income'] == 'More than 50000')] # Apenas se o tamanho da família seja igual a 6 ou tenha um ganho mensal maior que 50000

# Depois:
df.query("`Family size` == 6 or `Monthly Income` == 'More than 50000'") # Deve-se colocar o nome da coluna entre `` quando possuir espaços ou caracteres especiais em seu nome

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
5,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes
15,24,Female,Single,Student,No Income,Post Graduate,6,12.8893,77.6399,560068,Yes,Positive,Yes
32,25,Male,Married,Employee,More than 50000,Ph.D,4,12.9261,77.6221,560034,Yes,Positive,Yes
40,30,Male,Married,Self Employeed,More than 50000,Uneducated,4,12.9662,77.6068,560025,Yes,Negative,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,12.9369,77.6407,560095,Yes,Positive,Yes
373,30,Male,Married,Self Employeed,More than 50000,Graduate,1,13.0809,77.5565,560097,No,Negative,No
375,26,Female,Married,Employee,Below Rs.10000,Graduate,6,12.9859,77.6713,560093,No,Negative,No
376,25,Male,Single,Self Employeed,More than 50000,School,3,12.9859,77.6713,560093,Yes,Positive,Yes
380,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes

In [67]:
# Exemeplo 3: Utilizando condições com operador and e not

# Antes:
df[(df['Age'] == 19) & ~(df['Gender'] == 'Female')] # Caso idade seja igual a 19 e não seja mulher

# Depois:
df.query("Age == 19 and not Gender == 'Female'")

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
133,19,Male,Single,Student,No Income,Graduate,2,13.0019,77.5713,560003,No,Negative,No
196,19,Male,Single,Student,No Income,Graduate,6,12.9442,77.6076,560030,Yes,Positive,Yes
280,19,Male,Single,Student,No Income,Graduate,6,12.9048,77.6821,560036,Yes,Positive,Yes

In [72]:
# Exemeplo 4: Utilizando método isin

# Antes:
df[df['Occupation'].isin(['Self Employeed', 'House wife'])] # Mostra todas as fileiras que possuirem 'Self Employeed' e 'House wife' na coluna 'Occupation'

# Depois:
df.query("Occupation in ['Self Employeed', 'House wife']")

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
14,23,Female,Single,Self Employeed,10001 to 25000,Post Graduate,5,12.9438,77.5738,560004,Yes,Positive,Yes
37,32,Female,Prefer not to say,House wife,No Income,Graduate,5,12.9820,77.6256,560008,Yes,Negative,Yes
40,30,Male,Married,Self Employeed,More than 50000,Uneducated,4,12.9662,77.6068,560025,Yes,Negative,Yes
45,27,Female,Married,Self Employeed,10001 to 25000,Post Graduate,2,12.9261,77.6221,560034,Yes,Positive,Yes
89,28,Male,Married,Self Employeed,10001 to 25000,Graduate,2,13.0289,77.5400,560022,No,Negative,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,29,Male,Single,Self Employeed,More than 50000,Graduate,6,12.8845,77.6036,560076,Yes,Positive,Yes
361,24,Female,Single,Self Employeed,25001 to 50000,Post Graduate,3,13.0103,77.5796,560080,No,Negative,No
362,26,Male,Prefer not to say,Self Employeed,More than 50000,Post Graduate,2,13.0103,77.5796,560080,Yes,Positive,Yes
373,30,Male,Married,Self Employeed,More than 50000,Graduate,1,13.0809,77.5565,560097,No,Negative,No
376,25,Male,Single,Self Employeed,More than 50000,School,3,12.9859,77.6713,560093,Yes,Positive,Yes